schema {
  query: Query
  mutation: Mutation
}

type Query {
  # The directive makes the return value `FieldResult<String>`
  # rather than the default `FieldResult<&String>`
  helloWorld(name: String!): String! @juniper(ownership: "owned")
}

type Mutation {
  noop: Boolean!
}
